--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AEDXDEV/TempBan
build-by-default: true
branches:
- main
projects:
  TempBan:
    path: ""
    icon: "images/icon.png"
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.2.0
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.3
...
